language: cpp
#dist: trusty
compiler:
  - gcc
os:
- linux
cache:
  - apt

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
  - secure: "XTpmCY/ed1czuPQDoDjxB3oyoYHWqcoVg/YY3OLVR8DLEPfLVxgZlLfXC+Lmujr8aSW+Xwo2SNyVcaTh24wzBbVaUt57CD7FgTGA4R7kC6zmMOaXQyiNNwFUyB7daA9khWHDWvViTwUezjjDNKS3gmgWX2qlALlg/sYsivt6oDZJTNqkPVRunv8q3gehXinWrPEU6MYllkaIBFR5rCSUHQJwUd0bGl9urARxjpytXei+X1Y6lTtdn1ErIYOv6ve74nzzyxg4C6BUxAmiJa4xYrKTlkrzEM7IzGbN0tekO2P0bR7aFqunIZM5xDrIsZ5kYy2m+dWo4FnKwB02uEQ5dSKxyT5pRVrLbWi5R3AidiS/NJIni3O1D8wZWJzJ5R3Jp/zgLHxV4+rvaAj5vqHcqH5UCR7J6D4qq7qZeDg7irEFwYFQz4ZzgdAc3dqq5CdmPQStHrIdBBVtG3b6aae2KjVSA0NUa1jItDx1td98S2Js6Uf3RJqHEsHKEjm733HdYMdgbXjzOG4jCNZ0VyWj4ZM++gLuUKPohJfvOzNw12bCh1ph2rEzMHPe+beS3w5xhwHl8KAFdRhGGjY+ULC2b1m7PTGwtShH8n9pzBFoZ4NidqkDJT2qMMK4vuqAyAeLMOWx1pMHiOP9ET20EVHyn2UPM/bfjL53KCGX/43T1mQ="

addons:
  coverity_scan:
    project:
      name: "norihiro-w/ogs5-egs"
      description: "Build submitted via Travis CI"
    notification_email: norihiro.w@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DOGS_FEM=ON .."
    build_command:   "make"
    branch_pattern: coverity-scan


